### ISSUE TITLE
почему.. #1

### ISSUE THREAD

**Issue by maksgir** [MikhailDolinnyi/web_lab3_kotlin#1]
https://github.com/MikhailDolinnyi/web_lab3_kotlin/blob/0961d9a7a974cbb51e030a6eba0880f2b10d6d7b/src/main/webapp/js/main.js#L80

**Comment by MikhailDolinnyi** [comment]
Допустим хотим, чтоб x был равен 2, тогда
coords.x = 316
316-250 = 66
66 / 33 = 2
