### ISSUE TITLE
костыль #2

### ISSUE THREAD

**Issue by maksgir** [MikhailDolinnyi/web_lab3_kotlin#2]
https://github.com/MikhailDolinnyi/web_lab3_kotlin/blob/0961d9a7a974cbb51e030a6eba0880f2b10d6d7b/src/main/kotlin/ru/mikhail/lab3/dbobjects/Result.kt#L37
боль гибера + котлина, но можно обойтись без костыльного конструктора. поищи как

**Comment by MikhailDolinnyi** [comment]
йессерски, сделано по красоте, добавил котлин жпа plug ин
